package com.att.tdp.issueflow.audit;

import static org.assertj.core.api.Assertions.assertThat;

import com.att.tdp.issueflow.audit.domain.AuditLog;
import com.att.tdp.issueflow.audit.repository.AuditLogRepository;
import com.att.tdp.issueflow.audit.repository.AuditLogSpecifications;
import com.att.tdp.issueflow.common.enums.Actor;
import com.att.tdp.issueflow.common.enums.AuditAction;
import com.att.tdp.issueflow.common.enums.EntityType;
import com.att.tdp.issueflow.config.JpaConfig;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import java.time.Duration;
import java.time.Instant;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.data.jpa.domain.Specification;

/**
 * Persistence + dynamic-filter coverage for {@link AuditLogRepository} and
 * the {@link AuditLogSpecifications} helper. Verifies:
 *
 * <ol>
 *   <li>Persistence: required columns are stored, {@code @CreationTimestamp}
 *       populates {@code timestamp} on insert, the {@code diff} column
 *       round-trips JSON text, and SYSTEM-actor rows accept
 *       {@code performedBy=null}.</li>
 *   <li>Each {@link AuditLogSpecifications} filter narrows results in
 *       isolation (one test per filter).</li>
 *   <li>Filters AND-combine (spec 06 §6) — passing four together returns
 *       only the rows matching all four.</li>
 *   <li>Pagination + sort: {@code timestamp DESC} returns newest first; a
 *       size-2 request returns at most 2 rows and reports the right
 *       {@code totalElements}.</li>
 * </ol>
 *
 * <p>{@code @CreationTimestamp} is generated by Hibernate at flush time, so
 * inserts are interleaved with small {@code em.flush()} + sleeps in {@link
 * #seed()} to give each row a distinguishable timestamp without depending on
 * a monotonic-but-equal clock.
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Import(JpaConfig.class)
class AuditLogRepositoryJpaTest {

    @Autowired
    private AuditLogRepository repo;

    @PersistenceContext
    private EntityManager em;

    @BeforeEach
    void seed() throws InterruptedException {
        // Defensive wipe: the H2 in-mem DB persists across @SpringBootTest
        // classes in the same JVM (DB_CLOSE_DELAY=-1). AuditIntegrationTest is
        // NOT @Transactional and leaves rows behind; @DataJpaTest's per-method
        // rollback can't reach data committed by a different test class. Clear
        // here so the row-count assertions below stay deterministic regardless
        // of class-execution order.
        repo.deleteAll();
        em.flush();

        // Order matters: each insert flushes so its @CreationTimestamp is
        // strictly later than the previous row's. The 5ms sleep guards against
        // a clock with millisecond resolution returning identical values.
        save(AuditAction.CREATE, EntityType.TICKET, 1L, 100L, Actor.USER, null);
        Thread.sleep(5);
        save(AuditAction.UPDATE, EntityType.TICKET, 1L, 100L, Actor.USER, "{\"status\":\"TODO->IN_PROGRESS\"}");
        Thread.sleep(5);
        save(AuditAction.DELETE, EntityType.TICKET, 1L, 100L, Actor.USER, null);
        Thread.sleep(5);
        save(AuditAction.CREATE, EntityType.PROJECT, 99L, 100L, Actor.USER, null);
        Thread.sleep(5);
        save(AuditAction.AUTO_ASSIGN, EntityType.TICKET, 2L, null, Actor.SYSTEM, null);
        em.flush();
        em.clear();
    }

    private void save(AuditAction action, EntityType entityType, Long entityId,
                      Long performedBy, Actor actor, String diff) {
        AuditLog row = new AuditLog();
        row.setAction(action);
        row.setEntityType(entityType);
        row.setEntityId(entityId);
        row.setPerformedBy(performedBy);
        row.setActor(actor);
        row.setDiff(diff);
        em.persist(row);
        em.flush();
    }

    // ---- persistence --------------------------------------------------------

    @Test
    @DisplayName("persists all columns; @CreationTimestamp populates timestamp on insert")
    void should_persistAllColumns_andStampTimestamp() {
        AuditLog row = repo.findAll().get(0);

        assertThat(row.getId()).isNotNull();
        assertThat(row.getAction()).isNotNull();
        assertThat(row.getEntityType()).isNotNull();
        assertThat(row.getActor()).isNotNull();
        assertThat(row.getTimestamp()).isNotNull();
        // Just inserted — timestamp should be within seconds of now, not e.g.
        // epoch (which would mean the @CreationTimestamp isn't firing).
        assertThat(Duration.between(row.getTimestamp(), Instant.now()))
                .isLessThan(Duration.ofMinutes(1));
    }

    @Test
    @DisplayName("SYSTEM rows accept null performedBy; diff round-trips JSON text verbatim")
    void should_allowNullPerformedBy_andRoundTripDiff() {
        List<AuditLog> all = repo.findAll();

        AuditLog system = all.stream()
                .filter(r -> r.getActor() == Actor.SYSTEM)
                .findFirst().orElseThrow();
        assertThat(system.getPerformedBy()).isNull();

        AuditLog withDiff = all.stream()
                .filter(r -> r.getDiff() != null)
                .findFirst().orElseThrow();
        assertThat(withDiff.getDiff()).isEqualTo("{\"status\":\"TODO->IN_PROGRESS\"}");
    }

    // ---- specifications (one filter at a time) ------------------------------

    @Test
    @DisplayName("byEntityType: matches only rows of that type")
    void should_filterByEntityType() {
        var spec = Specification.where(AuditLogSpecifications.byEntityType(EntityType.PROJECT));

        List<AuditLog> result = repo.findAll(spec);

        assertThat(result).hasSize(1);
        assertThat(result.get(0).getEntityType()).isEqualTo(EntityType.PROJECT);
    }

    @Test
    @DisplayName("byAction: matches only rows of that action")
    void should_filterByAction() {
        var spec = Specification.where(AuditLogSpecifications.byAction(AuditAction.AUTO_ASSIGN));

        List<AuditLog> result = repo.findAll(spec);

        assertThat(result).hasSize(1);
        assertThat(result.get(0).getAction()).isEqualTo(AuditAction.AUTO_ASSIGN);
    }

    @Test
    @DisplayName("byActor: SYSTEM filter returns only background-job rows")
    void should_filterByActor() {
        var spec = Specification.where(AuditLogSpecifications.byActor(Actor.SYSTEM));

        List<AuditLog> result = repo.findAll(spec);

        assertThat(result).hasSize(1);
        assertThat(result.get(0).getActor()).isEqualTo(Actor.SYSTEM);
    }

    @Test
    @DisplayName("byEntityId: matches only rows for that entity")
    void should_filterByEntityId() {
        var spec = Specification.where(AuditLogSpecifications.byEntityId(1L));

        List<AuditLog> result = repo.findAll(spec);

        // Three rows touch ticket id=1 (CREATE / UPDATE / DELETE).
        assertThat(result).hasSize(3);
        assertThat(result).allMatch(r -> r.getEntityId().equals(1L));
    }

    @Test
    @DisplayName("null filter argument is a no-op — passes every row through")
    void should_treatNullFilter_asNoOp() {
        var spec = Specification.where(AuditLogSpecifications.byAction(null))
                .and(AuditLogSpecifications.byActor(null));

        List<AuditLog> result = repo.findAll(spec);

        assertThat(result).hasSize(5);
    }

    // ---- AND combination ---------------------------------------------------

    @Test
    @DisplayName("filters AND-combine: type+id+action+actor narrows to a single row")
    void should_combineFiltersWithAnd() {
        var spec = Specification.where(AuditLogSpecifications.byEntityType(EntityType.TICKET))
                .and(AuditLogSpecifications.byEntityId(1L))
                .and(AuditLogSpecifications.byAction(AuditAction.UPDATE))
                .and(AuditLogSpecifications.byActor(Actor.USER));

        List<AuditLog> result = repo.findAll(spec);

        assertThat(result).hasSize(1);
        assertThat(result.get(0).getAction()).isEqualTo(AuditAction.UPDATE);
        assertThat(result.get(0).getEntityId()).isEqualTo(1L);
    }

    // ---- pagination + sort -------------------------------------------------

    @Test
    @DisplayName("page request honours timestamp DESC and pageable totals")
    void should_paginate_andSortNewestFirst() {
        var pageable = PageRequest.of(0, 2, Sort.by(Sort.Direction.DESC, "timestamp"));

        Page<AuditLog> page = repo.findAll(Specification.where(null), pageable);

        assertThat(page.getContent()).hasSize(2);
        assertThat(page.getTotalElements()).isEqualTo(5);
        assertThat(page.getTotalPages()).isEqualTo(3);
        // The two newest rows are AUTO_ASSIGN (newest) and PROJECT/CREATE (next).
        assertThat(page.getContent().get(0).getAction()).isEqualTo(AuditAction.AUTO_ASSIGN);
        assertThat(page.getContent().get(1).getEntityType()).isEqualTo(EntityType.PROJECT);
    }
}
